#
# LoRa
#

obj-$(CONFIG_LORA_DEV) += lora-dev.o
lora-dev-y := dev.o

#
# Alphabetically sorted.
#

obj-$(CONFIG_LORA_RAK811) += lora-rak811.o
lora-rak811-y := rak811.o

obj-$(CONFIG_LORA_RN2483) += lora-rn2483.o
lora-rn2483-y := rn2483.o
lora-rn2483-y += rn2483_cmd.o

obj-$(CONFIG_LORA_SX125X) += lora-sx125x.o
lora-sx125x-y := sx125x_core.o

obj-$(CONFIG_LORA_SX125X_SPI) += lora-sx125x-spi.o
lora-sx125x-spi-y := sx125x_spi.o

obj-$(CONFIG_LORA_SX125X_CON) += lora-sx125x-con.o
lora-sx125x-con-y := sx125x_con.o

obj-$(CONFIG_LORA_SX1276) += lora-sx1276.o
lora-sx1276-y := sx1276.o

obj-$(CONFIG_LORA_SX1301) += lora-sx1301.o
lora-sx1301-y := sx1301.o

obj-$(CONFIG_LORA_TING01M) += lora-ting01m.o
lora-ting01m-y := ting01m.o
lora-ting01m-y += ting01m_cmd.o

obj-$(CONFIG_LORA_USI) += lora-usi.o
lora-usi-y := usi.o

obj-$(CONFIG_LORA_WIMOD) += lora-wimod.o
lora-wimod-y := wimod.o
